
emails:
  - super-admins
  - administrators

admin-access:
  - super-admins
  - administrators

sponsors:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - sponsors

sponsors-add:
  - super-admins
  - administrators
  - summit-front-end-administrators

sponsors-edit:
  - super-admins
  - administrators
  - summit-front-end-administrators

sponsors-extra-questions-edit:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - sponsors

sponsors-delete:
  - super-admins
  - administrators
  - summit-front-end-administrators

badge-scans:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - sponsors

badge-scans-edit:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - sponsors

admin-sponsors:
  - super-admins
  - administrators
  - summit-front-end-administrators

general:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-room-administrators
  - summit-registration-administrators
  - track-chairs-admins
  - sponsors

audit-log:
  - super-admins
  - administrators
  - summit-front-end-administrators

sponsorship-types:
  - super-admins
  - administrators
  - summit-front-end-administrators

summit-edit:
  - super-admins
  - administrators
  - summit-front-end-administrators

summit-add:
  - super-admins
  - administrators

summit-delete:
  - super-admins
  - administrators

speakers:
  - super-admins
  - administrators
  - summit-front-end-administrators

speakers-list:
  - super-admins
  - administrators
  - summit-front-end-administrators

speakers-edit:
  - super-admins
  - administrators
  - summit-front-end-administrators

speakers-add:
  - super-admins
  - administrators
  - summit-front-end-administrators

speakers-merge:
  - super-admins
  - administrators

speakers-delete:
  - super-admins
  - administrators

companies:
  - super-admins
  - administrators

sponsored-projects:
  - super-admins
  - administrators

attendees:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

events:
  - super-admins
  - administrators
  - summit-front-end-administrators
  -
voteable-presentations:
  - super-admins
  - administrators
  - summit-front-end-administrators

locations:
  - super-admins
  - administrators
  - summit-front-end-administrators

rsvp:
  - super-admins
  - administrators
  - summit-front-end-administrators

push-notifications:
  - super-admins
  - administrators
  - summit-front-end-administrators

tickets:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

registration-invitations:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

submissions-invitations:
  - super-admins
  - administrators
  - summit-front-end-administrators

room-occupancy:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-room-administrators

tags:
  - super-admins
  - administrators
  - summit-front-end-administrators

reports:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

purchase-orders:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

track-chairs:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - track-chairs-admins

badges:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

room-bookings:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

summitdocs:
  - super-admins
  - administrators
  - summit-front-end-administrators

email-flow-events:
  - super-admins
  - administrators
  - summit-front-end-administrators

tag-groups:
  - super-admins
  - administrators
  - summit-front-end-administrators

settings:
  - super-admins
  - administrators
  - summit-front-end-administrators

purchase_orders:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

progress-flags:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

signage:
  - super-admins
  - administrators
  - summit-front-end-administrators
