
emails:
  - super-admins
  - administrators

admin-access:
  - super-admins
  - administrators

sponsors:
  - super-admins
  - administrators

general:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-room-administrators
  - summit-registration-administrators
  - track-chairs-admins

summit-edit:
      - super-admins
      - administrators
      - summit-front-end-administrators

summit-add:
  - super-admins
  - administrators

summit-delete:
  - super-admins
  - administrators

speakers:
  - super-admins
  - administrators

companies:
  - super-admins
  - administrators

sponsored-projects:
  - super-admins
  - administrators

attendees:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

events:
  - super-admins
  - administrators
  - summit-front-end-administrators

locations:
  - super-admins
  - administrators
  - summit-front-end-administrators

rsvp:
  - super-admins
  - administrators
  - summit-front-end-administrators

push-notifications:
  - super-admins
  - administrators
  - summit-front-end-administrators

tickets:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

registration-invitations:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

room-occupancy:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-room-administrators

tags:
  - super-admins
  - administrators
  - summit-front-end-administrators

reports:
  - super-admins
  - administrators
  - summit-front-end-administrators

purchase-orders:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

track-chairs:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - track-chairs-admins

badges:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

room-bookings:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

summitdocs:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

email-flow-events:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

tag-groups:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

settings:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

purchase_orders:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators

progress-flags:
  - super-admins
  - administrators
  - summit-front-end-administrators
  - summit-registration-administrators